### ISSUE TITLE
esp-idf v5 compatibility

### ISSUE THREAD

**Issue by emanuelcima** [kerikun11/ESP32_VL53L0X#12]
Hi! I would love to use this component in my project, but I am using the latest version of esp-idf (v5) and I think (not sure) that it is not compatible.
I tried cloning the repository, including it in the `EXTRA_COMPONENT_DIRS` but when reconfiguring i get the following error

```
❯ idf.py reconfigure
...
CMake Error at build/_deps/espvl53l0x-src/CMakeLists.txt:19 (register_component):
  Unknown CMake command "register_component".
```

I did the following to make it work

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index efa0817..440e508 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,22 +1,39 @@
-set(COMPONENT_SRCS
-    api/core/src/vl53l0x_api.c
-    api/core/src/vl53l0x_api_calibration.c
-    api/core/src/vl53l0x_api_core.c
-    api/core/src/vl53l0x_api_ranging.c
-    api/core/src/vl53l0x_api_strings.c
-    api/platform/src/vl53l0x_platform.c
-    api/platform/src/vl53l0x_platform_log.c
-)
+cmake_minimum_required(VERSION 3.5)

-set(COMPONENT_ADD_INCLUDEDIRS
-    inc
-    api/core/inc
-    api/platform/inc
-)
+# set(COMPONENT_SRCS
+#     api/core/src/vl53l0x_api.c
+#     api/core/src/vl53l0x_api_calibration.c
+#     api/core/src/vl53l0x_api_core.c
+#     api/core/src/vl53l0x_api_ranging.c
+#     api/core/src/vl53l0x_api_strings.c
+#     api/platform/src/vl53l0x_platform.c
+#     api/platform/src/vl53l0x_platform_log.c
+# )

-set(COMPONENT_REQUIRES driver)
+# set(COMPONENT_ADD_INCLUDEDIRS
+#     inc
+#     api/core/inc
+#     api/platform/inc
+# )

-register_component()
+# set(COMPONENT_REQUIRES driver)
+
+idf_component_register(
+    SRCS
+    "api/core/src/vl53l0x_api.c"
+    "api/core/src/vl53l0x_api_calibration.c"
+    "api/core/src/vl53l0x_api_core.c"
+    "api/core/src/vl53l0x_api_ranging.c"
+    "api/core/src/vl53l0x_api_strings.c"
+    "api/platform/src/vl53l0x_platform.c"
+    "api/platform/src/vl53l0x_platform_log.c"
+    INCLUDE_DIRS
+    "inc"
+    "api/core/inc"
+    "api/platform/inc"
+    REQUIRES
+    "driver"
+)

 target_compile_definitions(${COMPONENT_TARGET}
     PRIVATE USE_I2C_2V8=1
```

Will making these changes be the only way to make it compatible with my project?

**Comment by na3eddin** [comment]
@emanuelcima  were you able to build it at least with the esp ide?
how did you do to build

**Comment by emanuelcima** [comment]
hey, what I did was clone the repository in my project, it was something very short-lived so I didn't care much. I think we can close this.

**Comment by kerikun11** [comment]
Hi @emanuelcima,

Thank you for using my library and I'm sorry for my late reply.

I tried building it with the latest ESP-IDF v5.1.2 in the state before the change, and it was able to be built without any errors.
Please check if the error still occurs.

**Comment by emanuelcima** [comment]
Yes, most likely the configuration of my work environment was not the best, I was using platformio and since I am not so familiar with building software using these tools I made some mistake in the process.

I'm going to close the issue, thank you very much for your response and for publishing this library that made using the sensor much easier for me!
