### ISSUE TITLE
esp ide version

### ISSUE THREAD

**Issue by na3eddin** [kerikun11/ESP32_VL53L0X#13]
hello don't you have an esp ide version, or is there a way to make it starting from your project?

**Comment by kerikun11** [comment]
ESP-IDF version is 3.3 or later.
Please see ESP-IDF document: [Build System - ESP32 - — ESP-IDF Programming Guide latest documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html)
