### ISSUE TITLE
ESP32s2 with VL53L0X reset issue

### ISSUE THREAD

**Issue by abdulwasey7** [kerikun11/ESP32_VL53L0X#5]
Hi there, 
I am working on esp32s2 and want to integrate the vl53l0x with esp32s2. 
Code is working fine with esp32.
But when I try to implement it on esp32s2 I get following reset issue

```
E (277) VL53L0X: VL53L0X_ResetDevice API status: -20 : Control Interface Error

E (3289) VL53L0X: VL53L0X_DataInit API status: -20 : Control Interface Error

E (3289) app_main: Failed to initialize VL53L0X :(

```
I connected the **gpio_xshut** pin for hardware reset but the issue remained the same...
```
  VL53L0X(i2c_port_t i2c_port = 0, gpio_num_t gpio_xshut = GPIO_NUM_4,
          gpio_num_t gpio_gpio1 = GPIO_NUM_MAX)
      : i2c_port(i2c_port), gpio_xshut(gpio_xshut), gpio_gpio1(gpio_gpio1) {
    vSemaphoreCreateBinary(xSemaphore);
  }

```
Any idea regarding the issue? kindly let me know if any other necessary detail is required

**Comment by kerikun11** [comment]
What GPIO number do you use for gpio_xshut?

**Comment by abdulwasey7** [comment]
GPIO_NUM_4

**Comment by kerikun11** [comment]
Are pull-up resistors connected to the I2C bus?

**Comment by abdulwasey7** [comment]
Yes using pull-ups
```
  void i2cMasterInit(int pin_sda = 8,
                     int pin_scl = 9, uint32_t freq = 400000) {
    i2c_config_t conf;
    conf.clk_flags = 0;
    conf.mode = I2C_MODE_MASTER;
    conf.sda_io_num = pin_sda;
    conf.sda_pullup_en = GPIO_PULLUP_ENABLE;
    conf.scl_io_num = pin_scl;
    conf.scl_pullup_en = GPIO_PULLUP_ENABLE;
    conf.master.clk_speed = freq;
    ESP_ERROR_CHECK(i2c_param_config(i2c_port, &conf));
    ESP_ERROR_CHECK(i2c_driver_install(i2c_port, conf.mode, 0, 0, 0));
  }
```
and I also attached 20k external pull-ups as well but the result is same.

**Comment by kerikun11** [comment]
According to VL53L0X's datasheet, the recommended resistor value is 1.5k to 2k Ohms.
see P. 8 of https://www.st.com/resource/en/datasheet/vl53l0x.pdf

**Comment by abdulwasey7** [comment]
used the 2k resistor but still same issue

**Comment by kerikun11** [comment]
Some dev boards uses GPIO9 as FSPIHD function.
Please try another pin?

**Comment by abdulwasey7** [comment]
used gpio10 instead of gpio9 but still facing same issue. Esp32 and esp32s2 both have same i2c fuctions according to documentation.

**Comment by abdulwasey7** [comment]
some hardware issue used other esp32s2 board and the issue is resolved thanks @kerikun11 for your help.
