### ISSUE TITLE
how to convert app_main.cpp to main.c 

### ISSUE THREAD

**Issue by abdulwasey7** [kerikun11/ESP32_VL53L0X#6]
Hi 
My previous code that I am using is in C and i m using esp-idf. This example runs fine but when I try to integrate this code with my existing C code I run into some issues. So is there any way that I convert this code into C so that I can intergate it with my code
Thanks

**Comment by kerikun11** [comment]
Can your code be converted to c++?

**Comment by abdulwasey7** [comment]
I tried but couldn't successed I think it is not possible for me to convert that code into c++. Is it possible to convert this Code to C ? if yes kindly guide me I will try to convert and will ask for help if I got stuck. Thanks

**Comment by abdulwasey7** [comment]
got it working used this code kindly check it out https://github.com/abdulwasey7/esp32_vl53lox_espidf
