### ISSUE TITLE
Failed to initialize VL53L0X

### ISSUE THREAD

**Issue by nikhil-robinson** [kerikun11/ESP32_VL53L0X#9]
Hi there i was testing this code on my esp32 and vl53lox and i am getting the bellow error

E (3350) VL53L0X: VL53L0X_ResetDevice API status: -7 : Time out error

E (3357) VL53L0X: VL53L0X_DataInit API status: -3 : Undefined error

E (3357) app_main: Failed to initialize VL53L0X :(

i have checked the pin configuration its all correct. i am using a ATK-PMW3901 module which has built in vl53lox

**Comment by kerikun11** [comment]
Try another development board to see if it's a HW issue.
